# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SearchForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(879, 867)

        intValidator = QtGui.QIntValidator()
        intValidator.setRange(0, 999999999)

        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(40, 60, 481, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("кроссовки")  # Search request

        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 130, 201, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setPlaceholderText("0")
        self.lineEdit_2.setValidator(intValidator)  # Min price

        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(320, 130, 201, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setPlaceholderText("10000")
        self.lineEdit_3.setValidator(intValidator)  # Max price

        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(320, 190, 201, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setPlaceholderText("100")
        self.lineEdit_4.setValidator(intValidator)  # Search radius

        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(320, 250, 201, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.setPlaceholderText("10")
        self.lineEdit_5.setValidator(intValidator)  # Pages

        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 320, 201, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_7.setPlaceholderText("2012")
        self.lineEdit_7.setValidator(intValidator)  # Registered after year

        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(320, 320, 201, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_6.setPlaceholderText("2021")
        self.lineEdit_6.setValidator(intValidator)  # Registered before year

        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(40, 390, 201, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_9.setPlaceholderText("1")
        self.lineEdit_9.setValidator(intValidator)  # Active goods min

        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(320, 390, 201, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_8.setPlaceholderText("150")
        self.lineEdit_8.setValidator(intValidator)  # Active goods max

        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(40, 450, 201, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_11.setPlaceholderText("0")
        self.lineEdit_11.setValidator(intValidator)  # Views min

        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(320, 450, 201, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_10.setPlaceholderText("1000")
        self.lineEdit_10.setValidator(intValidator)  # Views max

        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(40, 510, 481, 22))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_12.setPlaceholderText("1")
        self.lineEdit_12.setDisabled(True)
        self.lineEdit_12.setValidator(intValidator)  # ads posted in 30 days

        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(320, 580, 201, 22))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_13.setDisabled(True)

        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(40, 580, 201, 22))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_14.setDisabled(True)

        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(320, 640, 201, 22))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_15.setDisabled(True)

        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(40, 640, 201, 22))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_16.setDisabled(True)

        self.comboBox = QtWidgets.QComboBox(Form)  # City
        self.comboBox.setGeometry(QtCore.QRect(40, 190, 201, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(getCitiesList("goroda.txt"))

        self.comboBox_2 = QtWidgets.QComboBox(Form)  # Category
        self.comboBox_2.setGeometry(QtCore.QRect(40, 250, 201, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItems(getCategoriesList("categories.txt"))

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 110, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(320, 110, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 170, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(320, 170, 111, 16))
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 230, 81, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(320, 230, 111, 16))
        self.label_6.setObjectName("label_6")

        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(40, 300, 201, 16))
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(320, 300, 201, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(320, 370, 201, 16))
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(40, 370, 201, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(320, 430, 201, 16))
        self.label_11.setObjectName("label_11")

        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(40, 430, 201, 16))
        self.label_12.setObjectName("label_12")

        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(40, 490, 481, 16))
        self.label_13.setObjectName("label_13")

        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(320, 560, 201, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(40, 620, 201, 16))
        self.label_15.setObjectName("label_15")

        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(40, 560, 201, 16))
        self.label_16.setObjectName("label_16")

        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(320, 620, 201, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(40, 710, 221, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(40, 740, 221, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(40, 770, 221, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(40, 800, 221, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(40, 40, 301, 16))
        self.label_22.setObjectName("label_22")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(570, 60, 291, 151))

        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(340, 710, 81, 20))
        self.checkBox.setObjectName("checkBox")  # delivery included

        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(340, 740, 81, 20))
        self.checkBox_2.setObjectName("checkBox_2")  # Private seller

        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setGeometry(QtCore.QRect(340, 770, 81, 20))
        self.checkBox_3.setObjectName("checkBox_3")  # Delete puplicates
        self.checkBox_3.setChecked(True)

        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setGeometry(QtCore.QRect(340, 800, 81, 20))
        self.checkBox_4.setObjectName("checkBox_4")  # Delete without phone number
        self.checkBox_4.setChecked(True)

        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Цены от, руб"))
        self.label_2.setText(_translate("Form", "Цены до, руб"))
        self.label_3.setText(_translate("Form", "Город"))
        self.label_4.setText(_translate("Form", "Радиус поиска км"))
        self.label_5.setText(_translate("Form", "Категория"))
        self.label_6.setText(_translate("Form", "Кол-во страниц"))
        self.label_7.setText(_translate("Form", "Зарегистрирован позже чем год"))
        self.label_8.setText(_translate("Form", "Зарегистрирован до год"))
        self.label_9.setText(_translate("Form", "Активных товаров в продаже до"))
        self.label_10.setText(_translate("Form", "Активных товаров в продаже от"))
        self.label_11.setText(_translate("Form", "Просмотров до"))
        self.label_12.setText(_translate("Form", "Просмотров от"))
        self.label_13.setText(_translate("Form", "Объявлений за последние N дней"))
        self.label_14.setText(_translate("Form", "???"))
        self.label_15.setText(_translate("Form", "???"))
        self.label_16.setText(_translate("Form", "???"))
        self.label_17.setText(_translate("Form", "???"))
        self.label_18.setText(_translate("Form", "С доставкой"))
        self.label_19.setText(_translate("Form", "Только частные"))
        self.label_20.setText(_translate("Form", "Удалять дубликаты"))
        self.label_21.setText(_translate("Form", "Удалять без номера"))
        self.label_22.setText(_translate("Form", "Поисковый запрос"))
        self.pushButton.setText(_translate("Form", "Начать поиск"))


def getCitiesList(source):
    cityArray = set()
    with open(source, "r") as f:
        for i in f:
            cityArray.add(i.replace("\n", ""))
        cityArray.remove("")
    cities = list(cityArray)
    cities = sorted(cities)
    print(cities)
    return cities


def getCategoriesList(source):
    categoriesArray = list()
    with open(source, "r") as f:
        for i in f:
            categoriesArray.append(i.replace("\n", ""))
    print(categoriesArray)
    return categoriesArray


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
